src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use JetBrains\PhpStorm\Pure;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    Const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $title = null;

    /**
     * @ORM\Column(type="text")
     */
    private ?string $description = null;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $surface = null;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $rooms = null;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $bedrooms = null;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $floor = null;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $price = null;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $heat = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $city = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $address = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $postal_code = null;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $sold = null;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $updatedAt;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private ?float $lat = null;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private ?float $lng = null;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private Collection $options;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="properties")
     */
    private ?User $user;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="properties")
     */
    private ?Category $categories;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="property", orphanRemoval=true,cascade={"persist"})
     */
    private Collection $pictures;

    private ?Picture $picture = null;

    public function __construct()
    {
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(?float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(?float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        $this->options->removeElement($option);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategories(): ?Category
    {
        return $this->categories;
    }

    public function setCategories(?Category $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?Picture
    {
        return $this->picture;
    }

    public function setPicture(?Picture $picture): self
    {
        $this->picture = $picture;
        return $this;
    }
}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}BENIMMO Votre site immobilier{% endblock %}

{% block content %}
    {% include 'component/_properties.html.twig' %}
    {% include 'component/popular.html.twig' %}
    {% include 'component/newletter.html.twig' %}
    {% include 'component/discover.html.twig' %}
{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos bien' %}

{% block content %}
  <div class="jumbotron">
    <div class="container">
      {{ form_start(form) }}
      <div class="form-row align-items-end">
        <div class="col">
          {{ form_row(form.minSurface) }}
        </div>
        <div class="col">
          {{ form_row(form.maxPrice) }}
        </div>
        <div class="col">
          {{ form_row(form.options) }}
        </div>
        <div class="col">
          {{ form_row(form.address, {id: 'search_address'}) }}
        </div>
        <div class="col">
          {{ form_row(form.distance) }}
        </div>
        <div class="col">
          <div class="form-group">
            <button class="btn btn-primary">Rechercher</button>
          </div>
        </div>
      </div>
      {{ form_end(form) }}
    </div>
  </div>
  <div class="container mt-4">
    <h1>Voir tous nos biens</h1>

    <div class="row">
      {% for property in properties %}
        <div class="col-md-4">
          <div class="card" id="property-{{ property.id }}">
            {% for picture in property.pictures %}
              <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                <img src="{{ asset('uploads/' ~ picture.name) }}" alt="{{ property.title }}" class="card-img-top">
              </a>
            {% else%}
              <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                <img src="{{ asset('pictures/empty.jpg') }}" alt="" class="card-img-top">
              </a>
            {% endfor %}
            <div class="card-body">
              <h5 class="card-title">{{ property.title}}</h5>
              <p class="card-text">{{ property.surface }} m²</p>
              <p class="card-text">{{ property.city }} - {{ property.postalCode }}</p>
              <div class="card-title text-primary" style="font-weight: bold; font-size: 1.5rem;">
                {{ property.price | number_format(0, ',', ' ') }} €
              </div>
              <div>
                {% for category in property.categories %}
                  <em class="text-muted text-primary text-italic">{{ category.name }}</em>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="pagination">
      {{ knp_pagination_render(properties) }}
    </div>
  </div>
{% endblock %}

templates/pages/property.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voir tous nos biens{% endblock %}

{% block content %}
   <section class="section rent">
      <div class="container">
          {{ form_start(form) }}
          <div class="row">
              <div class="col-md-3">
                  {{ form_row(form.minSurface) }}
              </div>
              <div class="col-md-3">
                  {{ form_row(form.maxPrice) }}
              </div>
              <div class="col-md-3">
                  {{ form_row(form.options) }}
              </div>
              <div class="col-md-3">
                  {{ form_row(form.address, {id: 'search_address'}) }}
              </div>
              <div class="col-md-2">
                  {{ form_row(form.distance) }}
              </div>
              <br><br>
              <div class="text-center">
                  <div class="form-group">
                      <button class="btn btn-primary">Rechercher</button>
                  </div>
              </div>
          </div>
          {{ form_end(form) }}
      </div>
      <br>
      <div class="rent-center container">
         {% for property in properties %}
            <div class="box">
               <div class="top">
                  <a href="{{ path('property.show',  {slug: property.slug,'id': property.id}) }}">
                     <div class="overlay">
                        {% for picture in property.pictures %}
                           <img src="{{ asset('uploads/' ~ picture.name) }}" alt="{{ property.title }}">
                        {% else%}
                           <img src="{{ asset('pictures/empty.jpg') }}" alt="{{ property.title }}">
                        {% endfor %}
                     </div>
                     <div class="pos">
                        {% for category in property.categories %}
                           <span>{{ category.name }}</span>
                        {% endfor %}
                        <span>Achetez</span>
                     </div>
                  </a>
               </div>
               <div class="bottom">
                  <p>{{ property.title}}</p>
                   <p class="text-primary" style="font-size: 1.4rem;">{{ property.city}}&nbsp;({{ property.PostalCode }})</p>
                  <div>
                     <span>{{ property.price | number_format(0, ',', ' ') }} €</span>
                     <span><i class="far fa-eye"></i></span>
                  </div>
               </div>
            </div>
         {% else%}
          <p>Aucune recherche trouvée</p>
         {% endfor %}
      </div>
       <div style="padding-top: 12%"></div>
   </section>
{% endblock %}

templates/pages/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title}}{% endblock %}

{% block content %}
    <div class="jumbotron" style="padding-top: 20px;">
        <div class="container">
            <div class="mt-5">
                {{ include('component/flash_message.html.twig') }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    {% for picture in property.pictures %}
                        <div class="col">
                            <img src="{{ asset('uploads/' ~ picture.name) }}" style="width: 100%; height:auto;" alt="{{ property.title }}">
                        </div>
                    {% else%}
                        <img src="{{ asset('pictures/empty.jpg') }}" style="width: 100%; height:auto;" alt="">
                    {% endfor %}
                </div>
                 <div class="card col-md-3">
                     <br>
                     <img
                             class="rounded-circle"
                             width="250"
                             height="250"
                             src="{{ property.user.imageProfile is not null and property.user.imageProfile is not null ? '/uploads/' ~ property.user.imageProfile : '/pictures/avatar_defaut.png' }}"
                             alt=""
                     />
                     <div class="text-center">
                         <p>{{ property.user.lastname }} {{ property.user.firstname }}</p>
                         <p>{{ property.user.email }}</p>
                     </div>
                     <a href="" class="btn btn-primary">Envoyer un message</a>
                 </div>
            </div>
        </div>
    </div>
    <div class="container">
        <p>{{ property.description | nl2br }}</p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }}</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}